version: "3.8"

services:
  postgres:
    profiles:
      - development
    image: postgres:latest
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=sensor
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"