spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/sensor
    username: user
    password: user

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: update

  jackson:
    property-naming-strategy: SNAKE_CASE

logging:
  level:
    org:
      springframework:
        security: debug

jwt:
  duration: 1h
